name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages # Set a branch to deploy from
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All branches and history for GitHub Pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Publish the Next.js export directory
          cname: trisgiles.dev # Optional: if you have a custom domain